response_dict = {
    'Billing Issues': "We're sorry to hear about your billing issues. Please contact our customer service team at 999999999999 for assistance in resolving your billing concerns promptly. Your satisfaction is our top priority, and we're committed to providing you with a seamless experience. Thank you for your patience and understanding.",
    'Delivery Delays': "We apologize for any delivery delays you've experienced. Our team is working hard to resolve the issue and ensure timely deliveries. Your satisfaction is important to us, and we appreciate your patience. For further assistance or concerns, please contact to our customer executive.",
    'Product Quality': "We take product quality seriously. Please submit a complaint regarding your concern, and our team will address it promptly. Expect a member of our team to contact you soon to assist further.",
    'Customer Service': "Our customer service team is here to address your concerns promptly. Please contact customer-service@maccros.com our team member will reach out to you shortly to discuss and resolve any issues you may have. Your satisfaction is important to us, and we appreciate your patience. ",
    'Advertising Concerns': "To ensure a seamless experience with our advertising services, please email us at ad-concerns@maccros.com with detailed information about your concerns. Our team will prioritize addressing your issues promptly. We are committed to resolving any problems you may encounter. Thank you for choosing our services, and we look forward to assisting you soon.",
    'Ecommerce Platform Errors': "We apologize for any errors you’ve encountered on our ecommerce platform. Our technical team will work hard to resolve these issues as quickly as possible. Please try again later, and if the problem persists, contact our support team at support@maccros.com for further assistance. Thank you for your understanding and patience.",
    'other': "Thank you for reaching out to us. Unfortunately, I don't have enough information to address your query at the moment. Please submit a detailed complaint, and our team will get back to you as soon as possible.",
    'greeting': "Hello! How can I assist you today?",
    'thanks': "You're welcome! I'm happy to help. If you have any other questions or need further assistance, feel free to ask."
}
